<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>不确定数量的异步请求</title>
</head>
<body>

</body>
<script>
    function step(step,i) {
        let p = new Promise(function(resolve, reject){
            //做一些异步操作
            setTimeout(function(){
                console.log(step);
                resolve('随便什么数据'+i);
            }, 1000*i);
        });
        return p;
    }



    let arr =[];
    for(let i=0;i<3;i++){
        arr.push(step("输入数据"+i,i))
    }
    console.log(arr);

    //正确的方法
    Promise
        .all(arr)
        .then(function(results){
            console.log(results);
        });

    ////如果在.all内部加一个自运行函数，返回异步请求的一个数组。如下：
//    Promise
//        .all( (()=>{
//            let arr=[];
//            for(let i=0;i<3;i++){
//                arr.push(step("输入数据"+i,i))
//            }
//            return arr;
//        })())
//        .then(function(results){
//            console.log(results);
//        });
    //此时每个step函数都运行了两遍，=============可能是.all的内部如果写函数，则会自动运行一遍。同时函数本身也自运行了一遍

    //举例：如果消除自运行，则会先报错，再正常运行
//    Promise
//        .all( ()=>{
//            let arr=[];
//            for(let i=0;i<3;i++){
//                arr.push(step("输入数据"+i,i))
//            }
//            return arr;
//        })
//        .then(function(results){
//            console.log(results);
//        });
</script>
</html>